### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by noerb7** [gpunktschmitz/ConvertTo-Influxdb#1]
Hallo,
habe das script ausprobiert, bekomme aber leider den Fehler "/solar.influx Permission denied"
kann ich in der Befehlszeile des scripts den usernamen und das pw für die Datenbank angeben? Leider reichen meine Kenntnisse hier nicht mehr aus.

normalerweise komme ich in die db mit influx -username "user" -password "pw" und habe dort 2 datenbanken angelegt.

Bitte um Hilfestellung. Danke Norbert

**Comment by gpunktschmitz** [comment]
hi Norbert,
das Skript konvertiert einen influx export im Format CSV in eine Datei die man zum Import von Influx verwenden kann.

Was hast du genau eingegeben das zum Fehler "/solar.influx Permission denied" führt?

**Comment by noerb7** [comment]
Danke für die rasche Reaktion

Meine Eingabe war:
ConvertTo-Influx.ps1 -Path /media/usbstick/Messdaten55412.csv -Database solar > /solar.influx

Muss die csv Datei aus influx stammen? Ich schreibe bereits die aktuellen Daten in die DB (jsonstring und telegraf) und hätte gerne die alten Daten für Auswertungen auch in der DB. Allerdings sind die Daten nicht aus influx. Die Struktur der Datenbank sollte eigtl. passen.

**Comment by gpunktschmitz** [comment]
Ja, das Skript erwartet die Struktur eines influx Exports.

z.B. die Tabelle "temperaturmessungen" hat in meinem Export folgende Werte:
```
name,time,standort,value
temperatur,1538630108757483380,Wohnzimmer,22
temperatur,1538632808475044614,Wohnzimmer,23
```

Wenn du deine Daten in diese Form bringen kannst hilft dir mein Skript.

Das Skript prüft nicht ob die Daten im richtigen Format vorliegen; die Fehlermeldung kommt weil du versuchst nach "/" zu schreiben. Du musst die Ausgabe in ein Verzeichnis mit Schreibrechten leiten (z.B. "/tmp/solar.influx").

**Comment by noerb7** [comment]
Danke! Werde es demnächst noch einmal probieren.

**Comment by gpunktschmitz** [comment]
lass mich wissen wenn ich helfen kann. dieses issue schliesse ich erstmal.
